### PR TITLE
GH Release Actions

### PR DESCRIPTION
**Pull request by rfvermut**
Same as for main repo:
 - https://rfvermut.github.io/xESC/
 - https://github.com/rfvermut/xESC/releases/tag/v1.1.0

NB! Keep in mind that versioning need to be semantic. current `v1.01` won't work.

### CODE REVIEW

**Comment by ClemensElflein** [comment]
Thank you for the PR!
I'm not sure if it's the right thing to generate the files automatically here, because this repo has two designs: The STM32 and the RP2040 version of the ESC.

Now if I create a tag, it will build the RP2040 version and put it in the release, even if the release was meant for the STM32 version of the board.

I should probably create a new repo for the RP2040 version and then we can release them independently.

**Comment by rfvermut** [comment]
Splitting the repo seems like a right way to do if those are 2 completely independent projects.

**Comment by rfvermut** [comment]
@ClemensElflein could you at least create empty repos so I can prepare PRs into them to speed up the process?

**Comment by ClemensElflein** [comment]
done, I have moved the xESC2040 (because it's newer and therefore has less history here) to a new repo: https://github.com/ClemensElflein/xESC2040

**Comment by rfvermut** [comment]
Maybe it's worth removing non-2040 code from `PCB/` and moving 2040 directly into `PCB/`?

image

**Pull request closed without merging**
